[project]
name = "customer-service-chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.5.0",
    "dotenv>=0.9.9",
    "gradio>=6.5.1",
    "langchain-core>=1.2.9",
    "langgraph>=1.0.8",
    "langsmith>=0.6.9",
    "peft>=0.18.1",
    "streamlit>=1.54.0",
    "torch>=2.10.0",
    "transformers>=5.1.0",
    "trl>=0.27.2",
]



